In [40]:
from pandas import read_csv
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
import numpy

In [2]:
path = 'trainingdata.csv'
# Format: channel_acq,test_coupon,num_past_purch,spent_last_purchase,weeks_since_visit,browsing_minutes,shopping_cart,trans_after,revenue_after
# source: https://machinelearningmastery.com/tensorflow-tutorial-deep-learning-with-tf-keras/
trainingdata = read_csv(path, header=None)

path = 'testdata.csv'
testdata = read_csv(path, header=None)

# split into input and output columns
X, y = trainingdata.values[:, :-2], trainingdata.values[:, -2]


In [3]:
# ensure all data are floating point values
X = X.astype('float32')
# encode strings to integer
y = LabelEncoder().fit_transform(y)
# split into train and test datasets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)
# determine the number of input features


(2250, 7) (250, 7) (2250,) (250,)


In [4]:
trainingdata.values[:, -2]

array([0., 0., 0., ..., 1., 0., 0.])

In [5]:
n_features = X_train.shape[1]


# define model
model = Sequential()
model.add(Dense(10, activation='relu', kernel_initializer='he_normal', input_shape=(n_features,)))
model.add(Dense(8, activation='relu', kernel_initializer='he_normal'))
model.add(Dense(1, activation='sigmoid'))
# compile the model


model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
# fit the model
model.fit(X_train, y_train, epochs=150, batch_size=32, verbose=0)
# evaluate the model
loss, acc = model.evaluate(X_test, y_test, verbose=0)
print('Test Accuracy: %.3f' % acc)

Test Accuracy: 0.860


In [6]:
# make a prediction
row = [ 3.  ,  1.  ,  4.  , 51.99,  0.  , 14.  ,  1. ]
yhat = model.predict([row])
print('Predicted: %.3f' % yhat)

1/1 [==============================] - 0s 78ms/step
Predicted: 0.661


In [106]:
outputdata = []
X, y = testdata.values[:, :-2], testdata.values[:, -2:]
for i in range(len(testdata)):
    yhat = model.predict([list(X[i])])
    outputdata.append(numpy.append(numpy.append(X[i], y[i]), yhat))
    print(str(i) + "/" + str(len(testdata)))
    #print('Predicted: %.3f' % yhat)    
    #print(y[i])

1/1 [==============================] - 0s 35ms/step
0/2500
1/1 [==============================] - 0s 33ms/step
1/2500
1/1 [==============================] - 0s 32ms/step
2/2500
1/1 [==============================] - 0s 30ms/step
3/2500
1/1 [==============================] - 0s 36ms/step
4/2500
1/1 [==============================] - 0s 37ms/step
5/2500
1/1 [==============================] - 0s 33ms/step
6/2500
1/1 [==============================] - 0s 34ms/step
7/2500
1/1 [==============================] - 0s 36ms/step
8/2500
1/1 [==============================] - 0s 38ms/step
9/2500
1/1 [==============================] - 0s 35ms/step
10/2500
1/1 [==============================] - 0s 35ms/step
11/2500
1/1 [==============================] - 0s 34ms/step
12/2500
1/1 [==============================] - 0s 32ms/step
13/2500
1/1 [==============================] - 0s 33ms/step
14/2500
1/1 [==============================] - 0s 36ms/step
15/2500
1/1 [==============================] - 0s 32ms/ste

1/1 [==============================] - 0s 31ms/step
136/2500
1/1 [==============================] - 0s 32ms/step
137/2500
1/1 [==============================] - 0s 30ms/step
138/2500
1/1 [==============================] - 0s 31ms/step
139/2500
1/1 [==============================] - 0s 29ms/step
140/2500
1/1 [==============================] - 0s 29ms/step
141/2500
1/1 [==============================] - 0s 32ms/step
142/2500
1/1 [==============================] - 0s 31ms/step
143/2500
1/1 [==============================] - 0s 31ms/step
144/2500
1/1 [==============================] - 0s 30ms/step
145/2500
1/1 [==============================] - 0s 31ms/step
146/2500
1/1 [==============================] - 0s 31ms/step
147/2500
1/1 [==============================] - 0s 31ms/step
148/2500
1/1 [==============================] - 0s 30ms/step
149/2500
1/1 [==============================] - 0s 31ms/step
150/2500
1/1 [==============================] - 0s 30ms/step
151/2500
1/1 [===================

1/1 [==============================] - 0s 31ms/step
270/2500
1/1 [==============================] - 0s 30ms/step
271/2500
1/1 [==============================] - 0s 30ms/step
272/2500
1/1 [==============================] - 0s 29ms/step
273/2500
1/1 [==============================] - 0s 29ms/step
274/2500
1/1 [==============================] - 0s 29ms/step
275/2500
1/1 [==============================] - 0s 32ms/step
276/2500
1/1 [==============================] - 0s 29ms/step
277/2500
1/1 [==============================] - 0s 30ms/step
278/2500
1/1 [==============================] - 0s 31ms/step
279/2500
1/1 [==============================] - 0s 32ms/step
280/2500
1/1 [==============================] - 0s 31ms/step
281/2500
1/1 [==============================] - 0s 31ms/step
282/2500
1/1 [==============================] - 0s 31ms/step
283/2500
1/1 [==============================] - 0s 30ms/step
284/2500
1/1 [==============================] - 0s 31ms/step
285/2500
1/1 [===================

1/1 [==============================] - 0s 31ms/step
404/2500
1/1 [==============================] - 0s 32ms/step
405/2500
1/1 [==============================] - 0s 30ms/step
406/2500
1/1 [==============================] - 0s 31ms/step
407/2500
1/1 [==============================] - 0s 31ms/step
408/2500
1/1 [==============================] - 0s 29ms/step
409/2500
1/1 [==============================] - 0s 30ms/step
410/2500
1/1 [==============================] - 0s 30ms/step
411/2500
1/1 [==============================] - 0s 29ms/step
412/2500
1/1 [==============================] - 0s 28ms/step
413/2500
1/1 [==============================] - 0s 27ms/step
414/2500
1/1 [==============================] - 0s 29ms/step
415/2500
1/1 [==============================] - 0s 29ms/step
416/2500
1/1 [==============================] - 0s 28ms/step
417/2500
1/1 [==============================] - 0s 30ms/step
418/2500
1/1 [==============================] - 0s 29ms/step
419/2500
1/1 [===================

1/1 [==============================] - 0s 30ms/step
538/2500
1/1 [==============================] - 0s 30ms/step
539/2500
1/1 [==============================] - 0s 29ms/step
540/2500
1/1 [==============================] - 0s 30ms/step
541/2500
1/1 [==============================] - 0s 30ms/step
542/2500
1/1 [==============================] - 0s 29ms/step
543/2500
1/1 [==============================] - 0s 30ms/step
544/2500
1/1 [==============================] - 0s 31ms/step
545/2500
1/1 [==============================] - 0s 29ms/step
546/2500
1/1 [==============================] - 0s 31ms/step
547/2500
1/1 [==============================] - 0s 30ms/step
548/2500
1/1 [==============================] - 0s 29ms/step
549/2500
1/1 [==============================] - 0s 30ms/step
550/2500
1/1 [==============================] - 0s 31ms/step
551/2500
1/1 [==============================] - 0s 29ms/step
552/2500
1/1 [==============================] - 0s 30ms/step
553/2500
1/1 [===================

1/1 [==============================] - 0s 32ms/step
672/2500
1/1 [==============================] - 0s 32ms/step
673/2500
1/1 [==============================] - 0s 33ms/step
674/2500
1/1 [==============================] - 0s 35ms/step
675/2500
1/1 [==============================] - 0s 33ms/step
676/2500
1/1 [==============================] - 0s 33ms/step
677/2500
1/1 [==============================] - 0s 33ms/step
678/2500
1/1 [==============================] - 0s 35ms/step
679/2500
1/1 [==============================] - 0s 35ms/step
680/2500
1/1 [==============================] - 0s 32ms/step
681/2500
1/1 [==============================] - 0s 35ms/step
682/2500
1/1 [==============================] - 0s 35ms/step
683/2500
1/1 [==============================] - 0s 34ms/step
684/2500
1/1 [==============================] - 0s 33ms/step
685/2500
1/1 [==============================] - 0s 34ms/step
686/2500
1/1 [==============================] - 0s 35ms/step
687/2500
1/1 [===================

1/1 [==============================] - 0s 40ms/step
806/2500
1/1 [==============================] - 0s 33ms/step
807/2500
1/1 [==============================] - 0s 34ms/step
808/2500
1/1 [==============================] - 0s 35ms/step
809/2500
1/1 [==============================] - 0s 31ms/step
810/2500
1/1 [==============================] - 0s 28ms/step
811/2500
1/1 [==============================] - 0s 29ms/step
812/2500
1/1 [==============================] - 0s 30ms/step
813/2500
1/1 [==============================] - 0s 32ms/step
814/2500
1/1 [==============================] - 0s 30ms/step
815/2500
1/1 [==============================] - 0s 33ms/step
816/2500
1/1 [==============================] - 0s 32ms/step
817/2500
1/1 [==============================] - 0s 31ms/step
818/2500
1/1 [==============================] - 0s 32ms/step
819/2500
1/1 [==============================] - 0s 31ms/step
820/2500
1/1 [==============================] - 0s 30ms/step
821/2500
1/1 [===================

1/1 [==============================] - 0s 39ms/step
940/2500
1/1 [==============================] - 0s 51ms/step
941/2500
1/1 [==============================] - 0s 45ms/step
942/2500
1/1 [==============================] - 0s 45ms/step
943/2500
1/1 [==============================] - 0s 35ms/step
944/2500
1/1 [==============================] - 0s 40ms/step
945/2500
1/1 [==============================] - 0s 32ms/step
946/2500
1/1 [==============================] - 0s 35ms/step
947/2500
1/1 [==============================] - 0s 34ms/step
948/2500
1/1 [==============================] - 0s 39ms/step
949/2500
1/1 [==============================] - 0s 37ms/step
950/2500
1/1 [==============================] - 0s 37ms/step
951/2500
1/1 [==============================] - 0s 34ms/step
952/2500
1/1 [==============================] - 0s 34ms/step
953/2500
1/1 [==============================] - 0s 34ms/step
954/2500
1/1 [==============================] - 0s 35ms/step
955/2500
1/1 [===================

1/1 [==============================] - 0s 35ms/step
1073/2500
1/1 [==============================] - 0s 32ms/step
1074/2500
1/1 [==============================] - 0s 31ms/step
1075/2500
1/1 [==============================] - 0s 28ms/step
1076/2500
1/1 [==============================] - 0s 30ms/step
1077/2500
1/1 [==============================] - 0s 27ms/step
1078/2500
1/1 [==============================] - 0s 31ms/step
1079/2500
1/1 [==============================] - 0s 32ms/step
1080/2500
1/1 [==============================] - 0s 34ms/step
1081/2500
1/1 [==============================] - 0s 32ms/step
1082/2500
1/1 [==============================] - 0s 34ms/step
1083/2500
1/1 [==============================] - 0s 34ms/step
1084/2500
1/1 [==============================] - 0s 31ms/step
1085/2500
1/1 [==============================] - 0s 28ms/step
1086/2500
1/1 [==============================] - 0s 31ms/step
1087/2500
1/1 [==============================] - 0s 32ms/step
1088/2500
1/1 [===

1/1 [==============================] - 0s 30ms/step
1205/2500
1/1 [==============================] - 0s 30ms/step
1206/2500
1/1 [==============================] - 0s 36ms/step
1207/2500
1/1 [==============================] - 0s 31ms/step
1208/2500
1/1 [==============================] - 0s 29ms/step
1209/2500
1/1 [==============================] - 0s 30ms/step
1210/2500
1/1 [==============================] - 0s 30ms/step
1211/2500
1/1 [==============================] - 0s 29ms/step
1212/2500
1/1 [==============================] - 0s 30ms/step
1213/2500
1/1 [==============================] - 0s 33ms/step
1214/2500
1/1 [==============================] - 0s 32ms/step
1215/2500
1/1 [==============================] - 0s 29ms/step
1216/2500
1/1 [==============================] - 0s 30ms/step
1217/2500
1/1 [==============================] - 0s 30ms/step
1218/2500
1/1 [==============================] - 0s 30ms/step
1219/2500
1/1 [==============================] - 0s 35ms/step
1220/2500
1/1 [===

1/1 [==============================] - 0s 30ms/step
1337/2500
1/1 [==============================] - 0s 31ms/step
1338/2500
1/1 [==============================] - 0s 29ms/step
1339/2500
1/1 [==============================] - 0s 29ms/step
1340/2500
1/1 [==============================] - 0s 31ms/step
1341/2500
1/1 [==============================] - 0s 33ms/step
1342/2500
1/1 [==============================] - 0s 31ms/step
1343/2500
1/1 [==============================] - 0s 30ms/step
1344/2500
1/1 [==============================] - 0s 34ms/step
1345/2500
1/1 [==============================] - 0s 33ms/step
1346/2500
1/1 [==============================] - 0s 30ms/step
1347/2500
1/1 [==============================] - 0s 30ms/step
1348/2500
1/1 [==============================] - 0s 29ms/step
1349/2500
1/1 [==============================] - 0s 31ms/step
1350/2500
1/1 [==============================] - 0s 29ms/step
1351/2500
1/1 [==============================] - 0s 32ms/step
1352/2500
1/1 [===

1/1 [==============================] - 0s 37ms/step
1469/2500
1/1 [==============================] - 0s 36ms/step
1470/2500
1/1 [==============================] - 0s 33ms/step
1471/2500
1/1 [==============================] - 0s 29ms/step
1472/2500
1/1 [==============================] - 0s 31ms/step
1473/2500
1/1 [==============================] - 0s 30ms/step
1474/2500
1/1 [==============================] - 0s 31ms/step
1475/2500
1/1 [==============================] - 0s 30ms/step
1476/2500
1/1 [==============================] - 0s 30ms/step
1477/2500
1/1 [==============================] - 0s 29ms/step
1478/2500
1/1 [==============================] - 0s 32ms/step
1479/2500
1/1 [==============================] - 0s 34ms/step
1480/2500
1/1 [==============================] - 0s 31ms/step
1481/2500
1/1 [==============================] - 0s 30ms/step
1482/2500
1/1 [==============================] - 0s 31ms/step
1483/2500
1/1 [==============================] - 0s 30ms/step
1484/2500
1/1 [===

1/1 [==============================] - 0s 31ms/step
1601/2500
1/1 [==============================] - 0s 29ms/step
1602/2500
1/1 [==============================] - 0s 30ms/step
1603/2500
1/1 [==============================] - 0s 30ms/step
1604/2500
1/1 [==============================] - 0s 29ms/step
1605/2500
1/1 [==============================] - 0s 31ms/step
1606/2500
1/1 [==============================] - 0s 30ms/step
1607/2500
1/1 [==============================] - 0s 32ms/step
1608/2500
1/1 [==============================] - 0s 31ms/step
1609/2500
1/1 [==============================] - 0s 31ms/step
1610/2500
1/1 [==============================] - 0s 30ms/step
1611/2500
1/1 [==============================] - 0s 29ms/step
1612/2500
1/1 [==============================] - 0s 29ms/step
1613/2500
1/1 [==============================] - 0s 30ms/step
1614/2500
1/1 [==============================] - 0s 29ms/step
1615/2500
1/1 [==============================] - 0s 31ms/step
1616/2500
1/1 [===

1/1 [==============================] - 0s 32ms/step
1733/2500
1/1 [==============================] - 0s 33ms/step
1734/2500
1/1 [==============================] - 0s 32ms/step
1735/2500
1/1 [==============================] - 0s 35ms/step
1736/2500
1/1 [==============================] - 0s 30ms/step
1737/2500
1/1 [==============================] - 0s 29ms/step
1738/2500
1/1 [==============================] - 0s 30ms/step
1739/2500
1/1 [==============================] - 0s 29ms/step
1740/2500
1/1 [==============================] - 0s 29ms/step
1741/2500
1/1 [==============================] - 0s 28ms/step
1742/2500
1/1 [==============================] - 0s 32ms/step
1743/2500
1/1 [==============================] - 0s 30ms/step
1744/2500
1/1 [==============================] - 0s 32ms/step
1745/2500
1/1 [==============================] - 0s 30ms/step
1746/2500
1/1 [==============================] - 0s 29ms/step
1747/2500
1/1 [==============================] - 0s 30ms/step
1748/2500
1/1 [===

1/1 [==============================] - 0s 30ms/step
1865/2500
1/1 [==============================] - 0s 29ms/step
1866/2500
1/1 [==============================] - 0s 28ms/step
1867/2500
1/1 [==============================] - 0s 28ms/step
1868/2500
1/1 [==============================] - 0s 30ms/step
1869/2500
1/1 [==============================] - 0s 30ms/step
1870/2500
1/1 [==============================] - 0s 30ms/step
1871/2500
1/1 [==============================] - 0s 32ms/step
1872/2500
1/1 [==============================] - 0s 31ms/step
1873/2500
1/1 [==============================] - 0s 30ms/step
1874/2500
1/1 [==============================] - 0s 30ms/step
1875/2500
1/1 [==============================] - 0s 29ms/step
1876/2500
1/1 [==============================] - 0s 29ms/step
1877/2500
1/1 [==============================] - 0s 29ms/step
1878/2500
1/1 [==============================] - 0s 31ms/step
1879/2500
1/1 [==============================] - 0s 30ms/step
1880/2500
1/1 [===

1/1 [==============================] - 0s 33ms/step
1997/2500
1/1 [==============================] - 0s 34ms/step
1998/2500
1/1 [==============================] - 0s 32ms/step
1999/2500
1/1 [==============================] - 0s 30ms/step
2000/2500
1/1 [==============================] - 0s 29ms/step
2001/2500
1/1 [==============================] - 0s 29ms/step
2002/2500
1/1 [==============================] - 0s 31ms/step
2003/2500
1/1 [==============================] - 0s 30ms/step
2004/2500
1/1 [==============================] - 0s 28ms/step
2005/2500
1/1 [==============================] - 0s 32ms/step
2006/2500
1/1 [==============================] - 0s 31ms/step
2007/2500
1/1 [==============================] - 0s 31ms/step
2008/2500
1/1 [==============================] - 0s 30ms/step
2009/2500
1/1 [==============================] - 0s 31ms/step
2010/2500
1/1 [==============================] - 0s 30ms/step
2011/2500
1/1 [==============================] - 0s 30ms/step
2012/2500
1/1 [===

1/1 [==============================] - 0s 38ms/step
2129/2500
1/1 [==============================] - 0s 35ms/step
2130/2500
1/1 [==============================] - 0s 35ms/step
2131/2500
1/1 [==============================] - 0s 36ms/step
2132/2500
1/1 [==============================] - 0s 37ms/step
2133/2500
1/1 [==============================] - 0s 54ms/step
2134/2500
1/1 [==============================] - 0s 34ms/step
2135/2500
1/1 [==============================] - 0s 41ms/step
2136/2500
1/1 [==============================] - 0s 38ms/step
2137/2500
1/1 [==============================] - 0s 35ms/step
2138/2500
1/1 [==============================] - 0s 37ms/step
2139/2500
1/1 [==============================] - 0s 36ms/step
2140/2500
1/1 [==============================] - 0s 37ms/step
2141/2500
1/1 [==============================] - 0s 35ms/step
2142/2500
1/1 [==============================] - 0s 37ms/step
2143/2500
1/1 [==============================] - 0s 35ms/step
2144/2500
1/1 [===

1/1 [==============================] - 0s 35ms/step
2261/2500
1/1 [==============================] - 0s 34ms/step
2262/2500
1/1 [==============================] - 0s 31ms/step
2263/2500
1/1 [==============================] - 0s 31ms/step
2264/2500
1/1 [==============================] - 0s 30ms/step
2265/2500
1/1 [==============================] - 0s 31ms/step
2266/2500
1/1 [==============================] - 0s 32ms/step
2267/2500
1/1 [==============================] - 0s 31ms/step
2268/2500
1/1 [==============================] - 0s 35ms/step
2269/2500
1/1 [==============================] - 0s 34ms/step
2270/2500
1/1 [==============================] - 0s 31ms/step
2271/2500
1/1 [==============================] - 0s 29ms/step
2272/2500
1/1 [==============================] - 0s 29ms/step
2273/2500
1/1 [==============================] - 0s 30ms/step
2274/2500
1/1 [==============================] - 0s 29ms/step
2275/2500
1/1 [==============================] - 0s 31ms/step
2276/2500
1/1 [===

1/1 [==============================] - 0s 31ms/step
2393/2500
1/1 [==============================] - 0s 30ms/step
2394/2500
1/1 [==============================] - 0s 34ms/step
2395/2500
1/1 [==============================] - 0s 33ms/step
2396/2500
1/1 [==============================] - 0s 31ms/step
2397/2500
1/1 [==============================] - 0s 30ms/step
2398/2500
1/1 [==============================] - 0s 31ms/step
2399/2500
1/1 [==============================] - 0s 30ms/step
2400/2500
1/1 [==============================] - 0s 30ms/step
2401/2500
1/1 [==============================] - 0s 30ms/step
2402/2500
1/1 [==============================] - 0s 30ms/step
2403/2500
1/1 [==============================] - 0s 32ms/step
2404/2500
1/1 [==============================] - 0s 35ms/step
2405/2500
1/1 [==============================] - 0s 34ms/step
2406/2500
1/1 [==============================] - 0s 31ms/step
2407/2500
1/1 [==============================] - 0s 29ms/step
2408/2500
1/1 [===

In [107]:
outputdata[0:10]

[array([2.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        7.00000000e+00, 2.40000000e+01, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 1.83561649e-02]),
 array([  3.        ,   1.        ,   4.        , 120.98      ,
          5.        ,  29.        ,   1.        ,   0.        ,
          0.        ,   0.30458966]),
 array([1.        , 1.        , 0.        , 0.        , 0.        ,
        1.        , 1.        , 0.        , 0.        , 0.06738599]),
 array([ 3.        ,  1.        ,  2.        , 58.49      ,  0.        ,
        23.        ,  0.        ,  0.        ,  0.        ,  0.12690051]),
 array([1.00000000e+00, 1.00000000e+00, 2.00000000e+00, 2.65960000e+02,
        6.00000000e+00, 1.80000000e+01, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 4.88812756e-03]),
 array([3.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.29980000e+02,
        2.00000000e+00, 2.20000000e+01, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 4.013934

In [113]:
numpy.savetxt("outputdata.csv", outputdata, delimiter=",", fmt='%s')